name: win64-pdf2htmlEX

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-win64:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel git cmake ninja zip
            mingw-w64-x86_64-toolchain mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-poppler mingw-w64-x86_64-poppler-data
            mingw-w64-x86_64-cairo mingw-w64-x86_64-freetype
            mingw-w64-x86_64-libpng mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-libxml2 mingw-w64-x86_64-icu
            mingw-w64-x86_64-glib2 mingw-w64-x86_64-openjpeg2
            mingw-w64-x86_64-lcms2 mingw-w64-x86_64-harfbuzz
            mingw-w64-x86_64-fribidi mingw-w64-x86_64-zlib
            mingw-w64-x86_64-fontforge mingw-w64-x86_64-libspiro
            mingw-w64-x86_64-ntldd-git
          path-type: minimal
          cache: true

      - name: Fetch pdf2htmlEX sources
        shell: msys2 {0}
        run: |
          set -e
          git clone --depth 1 https://github.com/pdf2htmlEX/pdf2htmlEX.git source
          if [ -f source/CMakeLists.txt ]; then
            echo "SRCDIR=$PWD/source" >> $GITHUB_ENV
          elif [ -f source/pdf2htmlEX/CMakeLists.txt ]; then
            echo "SRCDIR=$PWD/source/pdf2htmlEX" >> $GITHUB_ENV
          else
            echo "::error ::CMakeLists.txt not found in cloned repo"; exit 1
          fi

      - name: Patch CMake minimum versions (to 3.5)
        shell: msys2 {0}
        run: |
          set -e
          find "$SRCDIR" -name CMakeLists.txt -print \
            -exec sed -i -E 's/cmake_minimum_required\s*\(\s*VERSION\s*[0-9.]+\)/cmake_minimum_required(VERSION 3.5)/g' {} +

      - name: Ensure FontForge import library exists
        shell: msys2 {0}
        run: |
          set -e
          if [ ! -f /mingw64/lib/libfontforge.dll.a ]; then
            echo "::error ::FontForge import library (libfontforge.dll.a) not found!"; exit 1
          fi

      - name: Configure
        shell: msys2 {0}
        env:
          PKG_CONFIG_EXECUTABLE: /mingw64/bin/pkg-config
          PKG_CONFIG_PATH: /mingw64/lib/pkgconfig
        run: |
          set -e
          cmake -S "$SRCDIR" -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH=/mingw64 \
            -DCMAKE_CXX_STANDARD=17 \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5

      - name: Build
        shell: msys2 {0}
        run: |
          set -e
          cmake --build build --parallel
          EXE=""
          [ -f build/pdf2htmlEX.exe ] && EXE="build/pdf2htmlEX.exe"
          [ -z "$EXE" ] && [ -f build/src/pdf2htmlEX.exe ] && EXE="build/src/pdf2htmlEX.exe"
          [ -z "$EXE" ] && { echo "::error ::pdf2htmlEX.exe not found after build"; ls -R build; exit 1; }
          strip "$EXE" || true
          echo "EXE=$EXE" >> $GITHUB_ENV

      - name: Bundle DLLs (portable dist)
        shell: msys2 {0}
        run: |
          set -e
          test -n "$EXE" || { echo "::error ::EXE path missing"; exit 1; }
          mkdir -p dist
          cp "$EXE" dist/
          ntldd -R dist/pdf2htmlEX.exe | awk '/=>/ {print $3}' | tr -d '\r' | sort -u | while read f; do
            [ -f "$f" ] && cp -u "$f" dist/ || true
          done
          if [ -d /mingw64/share/poppler ]; then
            mkdir -p dist/share
            cp -r /mingw64/share/poppler dist/share/
          fi
          ls -l dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf2htmlEX-win64-portable
          path: dist/**
