name: build-pdf2htmlex-windows-x64

on:
  workflow_dispatch:
  push:
    tags: [ 'v*' ]

jobs:
  build-windows-x64:
    runs-on: windows-latest
    env:
      MSYSTEM: UCRT64
      PKG_CONFIG_PATH: /ucrt64/lib/pkgconfig:/ucrt64/share/pkgconfig
    steps:
      - name: Checkout this repo (workflow + scripts)
        uses: actions/checkout@v4

      - name: Checkout upstream pdf2htmlEX sources
        uses: actions/checkout@v4
        with:
          repository: pdf2htmlEX/pdf2htmlEX
          path: upstream
          # For reproducible builds you can pin:
          # ref: v0.18.8.rc1

      - name: Verify source layout (Git-Bash)
        shell: bash
        run: |
          test -f upstream/pdf2htmlEX/CMakeLists.txt || { echo 'Missing CMakeLists in upstream/pdf2htmlEX'; ls -la upstream; ls -la upstream/pdf2htmlEX || true; exit 1; }

      - name: Set up MSYS2 (UCRT64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-pkg-config
            mingw-w64-ucrt-x86_64-poppler
            mingw-w64-ucrt-x86_64-poppler-data
            mingw-w64-ucrt-x86_64-cairo
            mingw-w64-ucrt-x86_64-fontforge
            mingw-w64-ucrt-x86_64-libspiro
            mingw-w64-ucrt-x86_64-libjpeg-turbo
            mingw-w64-ucrt-x86_64-libpng
            mingw-w64-ucrt-x86_64-freetype
            mingw-w64-ucrt-x86_64-fontconfig
            mingw-w64-ucrt-x86_64-libxml2
            mingw-w64-ucrt-x86_64-ntldd

      - name: Toolchain sanity check
        shell: msys2 {0}
        run: |
          gcc --version
          pkg-config --modversion poppler || true
          pkg-config --modversion poppler-cpp || true

      # Robust fix for your current configure error
      - name: Patch CMake policy floor (CMake >=3.5)
        shell: bash
        run: |
          set -e
          sed -i 's/^[[:space:]]*cmake_minimum_required(.*)$/cmake_minimum_required(VERSION 3.5)/I' upstream/pdf2htmlEX/CMakeLists.txt || true
          grep -qi '^[[:space:]]*cmake_minimum_required' upstream/pdf2htmlEX/CMakeLists.txt || sed -i '1i cmake_minimum_required(VERSION 3.5)' upstream/pdf2htmlEX/CMakeLists.txt

      - name: Configure (CMake + Ninja)
        shell: msys2 {0}
        env:
          CMAKE_POLICY_VERSION_MINIMUM: "3.5"   # modern CMake compatibility shim
        run: |
          cmake -S upstream/pdf2htmlEX -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH=/ucrt64 \
            -DFONTFORGE_INCLUDE_DIR=/ucrt64/include/fontforge \
            -DFONTFORGE_LIBRARY=/ucrt64/lib/libfontforge.dll.a \
            -Wno-dev

      - name: Build
        shell: msys2 {0}
        run: cmake --build build --config Release -j 2

      - name: Install to staging
        shell: msys2 {0}
        run: cmake --install build --prefix "${GITHUB_WORKSPACE}/_install"

      - name: Smoke-test CLI
        shell: msys2 {0}
        run: '"${GITHUB_WORKSPACE}/_install/bin/pdf2htmlEX.exe" --version || true'

      - name: Bundle exe + runtime DLLs + resources
        shell: msys2 {0}
        run: |
          set -euo pipefail
          mkdir -p dist/bin dist/share

          EXE="${GITHUB_WORKSPACE}/_install/bin/pdf2htmlEX.exe"
          test -f "$EXE" || { echo "pdf2htmlEX.exe not found: $EXE"; find "${GITHUB_WORKSPACE}/_install" -type f -iname '*pdf2htmlEX*.exe' -maxdepth 5 -print; exit 1; }

          cp "$EXE" dist/bin/

          pushd dist/bin >/dev/null
          ntldd -R "$(basename "$EXE")" | awk '/\/(ucrt64|mingw64)\// {print $3}' | xargs -I{} cp -u {} .
          popd >/dev/null

          if [ -d "${GITHUB_WORKSPACE}/_install/share/pdf2htmlEX" ]; then
            mkdir -p dist/share/pdf2htmlEX
            cp -r "${GITHUB_WORKSPACE}/_install/share/pdf2htmlEX/"* dist/share/pdf2htmlEX/
          fi

          for d in /ucrt64/share/poppler /mingw64/share/poppler; do
            if [ -d "$d" ]; then
              mkdir -p dist/share/poppler
              cp -r "$d"/* dist/share/poppler/ || true
            fi
          done

          7z a -tzip "${GITHUB_WORKSPACE}/pdf2htmlEX-windows-x64.zip" ./dist/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf2htmlEX-windows-x64
          path: pdf2htmlEX-windows-x64.zip

      - name: Create GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: pdf2htmlEX-windows-x64.zip
          generate_release_notes: true
