# .github/workflows/build-windows.yml
name: Cross-compile pdf2htmlEX for Windows

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          mingw-w64 \
          cmake \
          ninja-build \
          pkg-config \
          autoconf \
          automake \
          libtool \
          build-essential \
          libfontforge-dev \
          libjpeg-dev \
          libpng-dev \
          zlib1g-dev \
          libfreetype6-dev \
          libcairo2-dev \
          libpoppler-private-dev

    - name: Set up environment variables
      run: |
        echo 'CC=x86_64-w64-mingw32-gcc' >> $GITHUB_ENV
        echo 'CXX=x86_64-w64-mingw32-g++' >> $GITHUB_ENV
        echo 'RC=x86_64-w64-mingw32-windres' >> $GITHUB_ENV
        echo 'AR=x86_64-w64-mingw32-ar' >> $GITHUB_ENV
        echo 'RANLIB=x86_64-w64-mingw32-ranlib' >> $GITHUB_ENV
        echo 'STRIP=x86_64-w64-mingw32-strip' >> $GITHUB_ENV
        echo 'PKG_CONFIG_PATH=/usr/x86_64-w64-mingw32/lib/pkgconfig' >> $GITHUB_ENV
        echo 'CFLAGS=-O2' >> $GITHUB_ENV

    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake .. \
          -G Ninja \
          -DCMAKE_SYSTEM_NAME=Windows \
          -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc \
          -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ \
          -DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres \
          -DCMAKE_FIND_ROOT_PATH=/usr/x86_64-w64-mingw32 \
          -DCMAKE_INSTALL_PREFIX=/usr/x86_64-w64-mingw32 \
          -DCMAKE_BUILD_TYPE=Release
        ninja

    - name: Upload Windows binary
      uses: actions/upload-artifact@v3
      with:
        name: pdf2htmlEX-windows
        path: |
          build/pdf2htmlEX.exe
