name: build-pdf2htmlex-windows

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            base-devel
            git
            wget
            curl
            zip
            cmake
            ninja
            pkgconf
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-harfbuzz
            mingw-w64-x86_64-fontconfig
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-openjpeg2
            mingw-w64-x86_64-libtiff
            mingw-w64-x86_64-libxml2
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-lcms2
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-gettext
            mingw-w64-x86_64-libiconv
            mingw-w64-x86_64-libltdl
            mingw-w64-x86_64-libspiro
            mingw-w64-x86_64-poppler-data
            mingw-w64-x86_64-ntldd
          # cache pacman packages between runs
          cache: true

      - name: Build (MSYS2 bash)
        shell: msys2 {0}
        run: |
          bash ./scripts/build-msys2.sh

      - name: Upload artifact (portable zip)
        uses: actions/upload-artifact@v4
        with:
          name: pdf2htmlEX-windows-portable
          path: dist/pdf2htmlEX-windows-portable.zip
          if-no-files-found: error

  # Optional: attach artifact to a GitHub Release when pushing a tag like v0.18.8-windows
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pdf2htmlEX-windows-portable
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: pdf2htmlEX-windows-portable.zip
