name: Build pdf2htmlEX Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-poppler
          mingw-w64-x86_64-cairo
          mingw-w64-x86_64-freetype
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-libssh2
          make
          git

    - name: Build pdf2htmlEX
      shell: msys2 {0}
      run: |
        # Create build directory
        mkdir build
        cd build
        
        # Configure with CMake
        cmake .. \
          -G "MSYS Makefiles" \
          -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/install" \
          -DENABLE_TESTING=OFF
        
        # Build
        make -j$(nproc)
        
        # Install to specified directory
        make install

    - name: Package artifacts
      run: |
        # Create dist directory
        mkdir dist
        # Copy executable and required DLLs
        copy install\bin\pdf2htmlEX.exe dist\
        # Add any additional DLL dependencies here if needed
      shell: cmd

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pdf2htmlEX-windows-x64
        path: dist/
