name: win64-pdf2htmlEX

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-win64:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            base-devel
            git
            cmake
            ninja
            zip
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-poppler
            mingw-w64-x86_64-poppler-data
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-libxml2
            mingw-w64-x86_64-icu
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-fontforge
            mingw-w64-x86_64-ntldd-git

      - name: Fetch pdf2htmlEX sources (maintained fork)
        shell: msys2 {0}
        run: |
          set -e
          git clone --depth 1 --recursive https://github.com/pdf2htmlEX/pdf2htmlEX.git source
          # the CMake project is in the subdir:
          test -f source/pdf2htmlEX/CMakeLists.txt || { echo "::error ::CMakeLists not found in source/pdf2htmlEX"; exit 1; }

      - name: Configure (CMake + Ninja)
        shell: msys2 {0}
        env:
          PKG_CONFIG_EXECUTABLE: /mingw64/bin/pkg-config
          PKG_CONFIG_PATH: /mingw64/lib/pkgconfig
        run: |
          set -e
          cmake -S source/pdf2htmlEX -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH=/mingw64 \
            -DCMAKE_INSTALL_PREFIX=$PWD/dist-root \
            -DCMAKE_CXX_STANDARD=17
          cmake --build build --target help | head -n 50 || true

      - name: Build
        shell: msys2 {0}
        run: |
          set -e
          cmake --build build --config Release --parallel
          # exe may be in build/ or build/src/
          EXE=""
          [ -f build/pdf2htmlEX.exe ] && EXE="build/pdf2htmlEX.exe"
          [ -z "$EXE" ] && [ -f build/src/pdf2htmlEX.exe ] && EXE="build/src/pdf2htmlEX.exe"
          [ -z "$EXE" ] && { echo "::error ::pdf2htmlEX.exe not found"; ls -R build; exit 1; }
          strip "$EXE" || true
          echo "EXE=$EXE" >> $GITHUB_ENV

      - name: Bundle DLLs (portable dist)
        shell: msys2 {0}
        run: |
          set -e
          mkdir -p dist
          cp "$EXE" dist/
          ntldd -R dist/pdf2htmlEX.exe | awk '/=>/ {print $3}' | tr -d '\r' | sort -u | xargs -I{} cp -u {} dist/ || true
          # include poppler-data (cmaps etc.)
          mkdir -p dist/share/poppler
          if [ -d /mingw64/share/poppler ]; then
            (cd /mingw64/share && zip -r -9 "$GITHUB_WORKSPACE/poppler-share.zip" poppler >/dev/null)
            unzip -qq "$GITHUB_WORKSPACE/poppler-share.zip" -d dist/share
          fi
          ls -l dist/

      - name: Upload artifact (portable)
        uses: actions/upload-artifact@v4
        with:
          name: pdf2htmlEX-win64-portable
          path: dist/**
