name: build-win

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout (just to have a workspace)
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-poppler
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-harfbuzz
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-fontforge

      # === BUILD pdf2htmlEX (actual sources) ===
      - name: Fetch pdf2htmlEX sources
        shell: msys2 {0}
        run: |
          set -euxo pipefail
          PDF2HTMLEX_REPO=https://github.com/coolwanglu/pdf2htmlEX.git
          PDF2HTMLEX_REF=0.18.7-poppler-0.81.0
          git clone --depth 1 --branch "$PDF2HTMLEX_REF" "$PDF2HTMLEX_REPO" src
          test -f src/CMakeLists.txt
          grep -i pdf2htmlEX src/CMakeLists.txt || true

      - name: Configure & build
        shell: msys2 {0}
        working-directory: src
        run: |
          set -euxo pipefail
          rm -rf build && mkdir build && cd build
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/mingw64 \
            -DCMAKE_CXX_STANDARD=14 \
            -DENABLE_SVG=ON \
            ..
          ninja -v
          ninja install
          ls -l /mingw64/bin | sed -n '1,200p'

      - name: Verify pdf2htmlEX presence
        shell: msys2 {0}
        run: |
          set -euxo pipefail
          if [ ! -x /mingw64/bin/pdf2htmlEX.exe ]; then
            echo "::error title=pdf2htmlEX.exe missing::Build did not produce /mingw64/bin/pdf2htmlEX.exe"
            exit 1
          fi
          /mingw64/bin/pdf2htmlEX.exe --help >/dev/null 2>&1 || true

      # === PACKAGE (portable) ===
      - name: Assemble portable folder
        shell: msys2 {0}
        run: |
          set -euxo pipefail
          OUT="$GITHUB_WORKSPACE/out"
          mkdir -p "$OUT/bin"
          cp -v /mingw64/bin/pdf2htmlEX.exe "$OUT/bin/"
          cp -v /mingw64/bin/pdfinfo.exe     "$OUT/bin/"
          cp -v /mingw64/bin/pdftocairo.exe  "$OUT/bin/"
          cp -v /mingw64/bin/pdftoppm.exe    "$OUT/bin/"

          # data files
          if [ -d /mingw64/share/poppler ]; then
            mkdir -p "$OUT/share"
            cp -a /mingw64/share/poppler "$OUT/share/"
          fi

          # collect DLLs
          copy_deps () {
            ntldd -R "$1" | awk '/mingw64\/bin/ {print $3}' | while read -r dll; do
              [ -f "$dll" ] && cp -u "$dll" "$OUT/bin/"
            done
          }
          for exe in "$OUT/bin/"*.exe; do copy_deps "$exe"; done

          # common runtime DLLs (best effort)
          for dll in \
            /mingw64/bin/libstdc++-6.dll \
            /mingw64/bin/libgcc_s_seh-1.dll \
            /mingw64/bin/libwinpthread-1.dll ; do
            [ -f "$dll" ] && cp -u "$dll" "$OUT/bin/" || true
          done

          # guard again
          [ -x "$OUT/bin/pdf2htmlEX.exe" ] || (echo "::error pdf2htmlEX missing after packaging" && exit 1)

          # BUILD-INFO
          cat > "$OUT/BUILD-INFO" <<EOF
          run=${{ github.run_number }}
          commit=${{ github.sha }}
          date_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          runner=${{ runner.os }} (${MSYSTEM})
          poppler=$(pkg-config --modversion poppler || true)
          cairo=$(pkg-config --modversion cairo || true)
          freetype=$(pkg-config --modversion freetype2 || true)
          harfbuzz=$(pkg-config --modversion harfbuzz || true)
          EOF

          7z a -bd -tzip "$GITHUB_WORKSPACE/pdf2htmlEX-win64-${{ github.run_number }}.zip" "$OUT"/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf2htmlEX-win64
          path: pdf2htmlEX-win64-*.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          prerelease: true
          files: pdf2htmlEX-win64-*.zip
          body: |
            Automated Windows build for commit ${{ github.sha }}.
            The attached ZIP contains a BUILD-INFO file with component versions.
