name: build-pdf2htmlEX-windows

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >-
            base-devel
            git
            curl
            unzip
            wget
            tar
            patch
            cmake
            ninja
            pkgconf
            # runtime/build deps used by poppler/pdf2htmlEX
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-fontconfig
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-harfbuzz
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-openjpeg2
            mingw-w64-x86_64-libtiff
            mingw-w64-x86_64-lcms2
            mingw-w64-x86_64-libxml2
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-libcurl
            mingw-w64-x86_64-fontforge

      - name: Build all (MSYS2 bash)
        shell: msys2 {0}
        run: |
          set -euxo pipefail
          bash ./scripts/build-msys2.sh

      - name: Upload artifact (portable zip)
        uses: actions/upload-artifact@v4
        with:
          name: pdf2htmlEX-windows-portable
          path: dist/*
