name: Cross-compile pdf2htmlEX for Windows

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake bison flex g++ gperf \
          libtool libtool-bin make gettext texinfo unzip wget \
          p7zip-full python3 cmake ninja-build

    - name: Clone and build MXE (cross-compiler)
      run: |
        git clone https://github.com/mxe/mxe.git
        cd mxe
        make MXE_TARGETS='x86_64-w64-mingw32.static' \
             qtbase cairo freetype fontconfig jpeg libpng zlib \
             glib poppler fontforge \
             -j$(nproc)

    - name: Build pdf2htmlEX
      run: |
        export PATH=$PWD/mxe/usr/bin:$PATH
        export CROSS="x86_64-w64-mingw32.static"

        # Clone and checkout a compatible version
        git clone https://github.com/coolwanglu/pdf2htmlEX.git
        cd pdf2htmlEX
        git checkout tags/0.14.6

        mkdir build
        cd build

        cmake .. \
          -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/mxe/usr/$CROSS/share/cmake/mxe-conf.cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=../install

        ninja pdf2htmlEX

        mkdir -p output
        cp src/pdf2htmlEX.exe output/

    - name: Upload Windows binary
      uses: actions/upload-artifact@v3
      with:
        name: pdf2htmlEX-windows
        path: pdf2htmlEX/build/output/pdf2htmlEX.exe
