name: build-win
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel git zip unzip p7zip
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-poppler
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-harfbuzz
            mingw-w64-x86_64-fontforge
        # All subsequent `shell: msys2 {0}` steps run in MSYS2

      - name: Build pdf2htmlEX
        shell: msys2 {0}
        run: |
          set -euxo pipefail
          # … your existing build here …
          # make install or place pdf2htmlEX.exe in /mingw64/bin

      - name: Package binaries + BUILD-INFO
        shell: msys2 {0}
        run: |
          set -euxo pipefail
          out="$GITHUB_WORKSPACE/out"
          mkdir -p "$out/bin" "$out/share"

          cp /mingw64/bin/pdf2htmlEX.exe "$out/bin/" || true
          cp /mingw64/bin/pdfinfo.exe    "$out/bin/" || true
          cp /mingw64/bin/pdftocairo.exe "$out/bin/" || true
          cp /mingw64/bin/pdftoppm.exe   "$out/bin/" || true

          if [ -d /mingw64/share/poppler ]; then
            cp -r /mingw64/share/poppler "$out/share/"
          fi

          {
            echo "repo=${GITHUB_REPOSITORY}"
            echo "run=${GITHUB_RUN_NUMBER}"
            echo "commit=${GITHUB_SHA}"
            echo "date_utc=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            echo "runner=windows-latest (MSYS2)"
            command -v /mingw64/bin/pdf2htmlEX.exe >/dev/null 2>&1 && echo "pdf2htmlEX=$(/mingw64/bin/pdf2htmlEX.exe --version 2>&1 | tr -d '\r')" || true
            pkg-config --modversion poppler    >/dev/null 2>&1 && echo "poppler=$(pkg-config --modversion poppler)"         || true
            pkg-config --modversion cairo      >/dev/null 2>&1 && echo "cairo=$(pkg-config --modversion cairo)"             || true
            pkg-config --modversion freetype2  >/dev/null 2>&1 && echo "freetype=$(pkg-config --modversion freetype2)"     || true
            pkg-config --modversion fontforge  >/dev/null 2>&1 && echo "fontforge=$(pkg-config --modversion fontforge)"    || true
          } > "$out/BUILD-INFO"

          (cd "$out/.." && 7z a -r "pdf2htmlEX-win64-${GITHUB_RUN_NUMBER}.zip" "out")

      - name: Create GitHub Release + upload asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "pdf2htmlEX Windows build ${{ github.run_number }}"
          body: |
            Automated Windows build for commit ${{ github.sha }}.
            ✅ The attached ZIP contains a BUILD-INFO file with component versions.
          prerelease: true
          files: |
            pdf2htmlEX-win64-${{ github.run_number }}.zip
