- name: Create GitHub Release
  uses: softprops/action-gh-release@v2
  if: github.ref == 'refs/heads/main'
  with:
    tag_name: v${{ github.run_number }}
    name: pdf2htmlEX Windows build ${{ github.run_number }}
    draft: false
    prerelease: true

- name: Upload asset to Release
  uses: softprops/action-gh-release@v2
  if: github.ref == 'refs/heads/main'
  with:
    files: pdf2htmlEX-win64.zip
